name: delegate

on:
  workflow_call:
    inputs:
      pr_number:
        required: false
        type: number
    secrets:
      token:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running centralized workflow from repo B"
      - run: echo "PR number = ${{ inputs.pr_number }}"
